// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdiDo4E4akT9J3HCi_FAyRKjY1inqM-1c',
    appId: '1:455882995912:web:46aa8b0e3d43e5d6e48dfd',
    messagingSenderId: '455882995912',
    projectId: 'chat-group-6c509',
    authDomain: 'chat-group-6c509.firebaseapp.com',
    storageBucket: 'chat-group-6c509.firebasestorage.app',
    measurementId: 'G-FX8Y7BBYNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQ7VIZW1X2OJu_1jVOxh24xNLUO_PhMw',
    appId: '1:455882995912:android:092f159b7bb03bcfe48dfd',
    messagingSenderId: '455882995912',
    projectId: 'chat-group-6c509',
    storageBucket: 'chat-group-6c509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaqR2v2UMrdyxugvQsXS3qzanrse5dtg',
    appId: '1:455882995912:ios:f547117792123e87e48dfd',
    messagingSenderId: '455882995912',
    projectId: 'chat-group-6c509',
    storageBucket: 'chat-group-6c509.firebasestorage.app',
    iosBundleId: 'com.example.chatGroup',
  );
}
