class Textmanager {
  Textmanager._();
  static String ksignin = "Sign in";
  static String ksignup = "Sign up";
  static String kOr = "   or continue with   ";
  static String klogin = "Log in";
  static String kcontinue = "Continue";
  static String kEnterPassword = "Enter your Password";
  static String kEnterEmail = "Enter your Email";
  static String kForgetPassword = 'Forgot Password?';
  static String kHaveAccount = 'Already have an account?';
  static String kNotHaveAccount = "Don't have an account?";
  static String kSendMessage = "Write your Message here";
  static String kProfilephoto = "Profile photo";
  static String kPersonalProfile = "Personal Profile";
  static String kProfile = "Profile";
  static String kCamera = 'Camera';
  static String kGallery = 'Gallery';
  static String kCompleteprofile = "Complete your profile";
  static String kStartchat = "Start Chat";
  static String kSelectCountry = "Select Country";
  static String kSelectGender = "Select Gender";
  static String kGender = "Gender";
  static String kMale = "Male";
  static String kFemale = "Female";
  static String kChat = "Chat";
  static String kFullName = "Full Name";
  static String kPhoneNumber = "Phone Number";
  static String k000000000 = "000 000 000";
  static String kCountry = "Country";
  static String kDateOfBrith = "Date Of Brith";
  static String kPhone = "Phone";
  static String kName = "Name";
  static String kEmail = "Email";
}
